In [2]:
import numpy as np

**Create ndarray(n-dimensional):**

In [3]:
# Create a 1D ndarray that contains only integers
x = np.array([1,2,3,4,5])
print('X is ',x)
print('Dimension of x ',x.shape)
print('Elements in the x are of type:',x.dtype)

X is  [1 2 3 4 5]
Dimension of x  (5,)
Elements in the x are of type: int64


In [4]:
# Create a rank 2 ndarray that only contains integers
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print('Y has dimensions:',y.shape)
print('Y has total',y.size,'elements')
print('Y is an object of type:', type(y))
print('The elementsin the y are of type',y.dtype)

Y has dimensions: (4, 3)
Y has total 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elementsin the y are of type int64


**Create ndarray with dtype**

In [5]:
# Specify the dtype when creating the ndarray
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype= np.int64)
x

array([1, 2, 3, 4, 5])

**Zeros**

In [6]:
# Create ndarray using built-in functions
# 3 x 4 ndarray full of zeros
# np.zeros(shape)
X = np.zeros((3,4))
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Ones**

In [7]:
# a 3 x 2 ndarray full of ones
# np.ones(shape)
X = np.ones((3,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

**Full**

In [8]:
# 2 x 3 ndarray full of fives
# np.full(shape, constant value)
X = np.full((3,4),5)
X

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

**Identity Matrix**

In [9]:
# Identity Matrix
# Since all Identity Matrices are square, the np.eye() function only takes a single integer as an argument
# 5 x 5 Identity matrix
X = np.eye(5)
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Diagonal Matrix**

In [10]:
# Diagonal Matrix
# 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50 on its main diagonal
x = np.diag([10,20,30,50])
x

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 50]])

**Arange**

In [11]:
# 1D array that has sequential integers from 0 to 9
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# 1 ndarray that has sequential integers from 4 to 9
# [start,stop]
x = np.arange(4,10)
x

array([4, 5, 6, 7, 8, 9])

In [13]:
# 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
# np.arange(start,stop,step)
x = np.arange(1,14,3)
x

array([ 1,  4,  7, 10, 13])

**Linspace**

In [14]:
# Even though the np.arange() function allows for non-integer steps,
# such as 0.3, the output is usually inconsistent, due to the finite
# floating point precision. For this reason, in the cases where
# non-integer steps are required, it is usually better to use linspace()
# becayse np.linspace() uses the number of elements we want in a
# particular interval, instead of the step between values.
# linspace returns N evenly spaced numbers over the closed interval [start, stop]
# np.linspace(start, stop, N)
x = np.linspace(0,25,10)
x

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [15]:
5.55555556-2.77777778 # interval is same

2.77777778

**Reshape**

In [16]:
# np.reshape(ndarray, new_shape)
# converts the given ndarray into the specified new_shape
y = np.arange(20)
print('y = ', y)
x = np.reshape(y,(4,5))
print('x = ',x)

y =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
x =  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [17]:
# or
x = np.arange(20).reshape(4, 5) # does the same thing as above
# and the same thing with with linshape
y = np.linspace(0,50,10, endpoint=False).reshape(5,2)
# One great feature about NumPy, is that some functions can also be
# applied as methods. This allows us to apply different functions in
# sequence in just one line of code

**Slicing**

In [18]:
# ndarray[start:end]
# ndarray[start:]
# ndarray[:end]
# ndarray[<start>:<stop>:<step>]

# In methods one and three, the end index is excluded [,)
X = np.arange(20).reshape(4,5)
print('x:',x)

# select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns


x: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [19]:
Z = X[1:4,2:5]
print(Z)
# or
C = X[1:,2:5]
print(C)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [20]:
# elements = a_list[<start>:<stop>:<step>]
# select all the elements in the 3rd row
v = X[2,:]
v

array([10, 11, 12, 13, 14])

In [21]:
# select all the elements in the 3rd column
u = X[:,2]
u

array([ 2,  7, 12, 17])

In [22]:
# select all the elements in the 3rd column but return a rank 2 ndarray
w = X[:,2:3]
w

array([[ 2],
       [ 7],
       [12],
       [17]])

In [23]:
# Note: Slicing creates a view, not a copy
# when we make assignments, such as: Z = X[1:4,2:5]
# the slice of the original array X is not copied in the variable Z.
# Rather, X and Z are now just two different names for the same ndarray.
# We say that slicing only creates a view of the original array.
# This means if we make changes to Z, X changes as well.

**Random**

In [24]:
# 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
# np.random.random(shape)
X = np.random.random((3,3))
X

array([[0.00319718, 0.79944921, 0.15879984],
       [0.43724317, 0.19099021, 0.94200805],
       [0.34074948, 0.1527913 , 0.61082179]])

In [25]:
# np.random.randint(start, stop, size = shape)
# [start, stop)
X = np.random.randint(4, 15, size = (3,2))
X

array([[11,  7],
       [ 4, 10],
       [10,  5]])

In [26]:
# create ndarrays with random numbers that satisfy certain statistical properties
# 1000 x 1000 ndarray of random floats drawn from normal (Gaussian)
# distribution with a mean of zero and a standard deviation of 0.1.
# np.random.normal(mean, standard deviation, size=shape)
X = np.random.normal(0, 0.1, size=(1000,1000))
X

array([[ 0.09863847, -0.06971271,  0.06651079, ...,  0.14675521,
        -0.01227825, -0.05321641],
       [-0.03208328, -0.04013378, -0.00968445, ...,  0.03784811,
        -0.12380762,  0.03144504],
       [ 0.10199924, -0.01843964,  0.05726711, ..., -0.0297969 ,
         0.05289063, -0.13965224],
       ...,
       [ 0.07755977, -0.00323403, -0.10511335, ...,  0.16890702,
        -0.05406659,  0.06205203],
       [-0.05470706,  0.04092344, -0.03194074, ..., -0.1142675 ,
        -0.15054613, -0.10752059],
       [ 0.08327789, -0.09730403, -0.06821319, ...,  0.07201153,
        -0.09113618, -0.04723483]])

**Mutability**

In [27]:
# Change ndarray
x[3] = 20
X[0,0] = 20

**Delete**

In [28]:
# np.delete(ndarray, elements, axis)
x = np.array([1, 2, 3, 4, 5])
# delete the first and fifth element of x
x = np.delete(x, [0,4])
x

array([2, 3, 4])

In [29]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
# delete the first row of Y
w = np.delete(Y, 0, axis=0)
w

array([[4, 5, 6],
       [7, 8, 9]])

In [30]:
# delete the first and last column of Y
v = np.delete(Y, [0,2], axis=1)
v

array([[2],
       [5],
       [8]])

**Append**

In [31]:
# np.append(ndarray, elements, axis)
# append the integer 6 to x
x = np.append(x, 6)
x

array([2, 3, 4, 6])

In [33]:
# append the integer 7 and 8 to x
x = np.append(x, [7,8])
x

array([2, 3, 4, 6, 7, 8, 7, 8])

In [34]:
# append a new row containing 7,8,9 to y
v = np.append(Y, [[10,11,12]], axis=0)
v

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
# append a new column containing 9 and 10 to y
q = np.append(Y,[[13],[14],[15]], axis=1)
q

array([[ 1,  2,  3, 13],
       [ 4,  5,  6, 14],
       [ 7,  8,  9, 15]])

**Insert**

In [37]:
# np.insert(ndarray, index, elements, axis)
# inserts the given list of elements to ndarray right before
# the given index along the specified axis
x = np.array([1, 2, 5, 6, 7])
Y = np.array([[1,2,3],[7,8,9]])
# insert the integer 3 and 4 between 2 and 5 in x.
x = np.insert(x,2,[3,4])
x

array([1, 2, 3, 4, 5, 6, 7])

In [39]:
# insert a row between the first and last row of Y
w = np.insert(Y,1,[4,5,6],axis=0)
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
# insert a column full of 5s between the first and second column of Y
v = np.insert(Y,1,5,axis=1)
v

array([[1, 5, 2, 3],
       [7, 5, 8, 9]])

**Stacking**

In [42]:
# NumPy also allows us to stack ndarrays on top of each other,
# or to stack them side by side. The stacking is done using either
# the np.vstack() function for vertical stacking, or the np.hstack()
# function for horizontal stacking. It is important to note that in
# order to stack ndarrays, the shape of the ndarrays must match.
x = np.array([1,2])
Y = np.array([[3,4],[5,6]])
z = np.vstack((x,Y))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
w = np.hstack((Y,x.reshape(2,1)))
w

array([[3, 4, 1],
       [5, 6, 2]])

**Copy**

In [ ]:
# if we want to create a new ndarray that contains a copy of the
# values in the slice we need to use the np.copy()
# create a copy of the slice using the np.copy() function
Z = np.copy(X[1:4,2:5])
#  create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()

**Find Unique Elements**


In [ ]:
# Find Unique Elements in ndarray
u = np.unique(X)

**Boolean Indexing**

In [45]:
X = np.arange(25).reshape(5, 5)
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

# use Boolean indexing to assign the elements that
# are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1
X

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, -1, -1, -1, -1],
       [-1, -1, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**Set Operations**

In [46]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


**Sorting**

In [ ]:
# When used as a function, it doesn't change the original ndarray
s = np.sort(x)
# When used as a method, the original array will be sorted
x.sort()

# sort x but only keep the unique elements in x
s = np.sort(np.unique(x))

# sort the columns of X
s = np.sort(X, axis = 0)

# sort the rows of X
s = np.sort(X, axis = 1)

**Math Functions**


In [47]:
# NumPy allows element-wise operations on ndarrays as well as
# matrix operations. In order to do element-wise operations,
# NumPy sometimes uses something called Broadcasting.
# Broadcasting is the term used to describe how NumPy handles
# element-wise arithmetic operations with ndarrays of different shapes.
# For example, broadcasting is used implicitly when doing arithmetic
# operations between scalars and ndarrays.
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])
np.add(x,y)
np.subtract(x,y)
np.multiply(x,y)
np.divide(x,y)

array([0.18181818, 0.30769231, 0.4       , 0.47058824])

In [ ]:
# in order to do these operations the shapes of the ndarrays
# being operated on, must have the same shape or be broadcastable
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)
np.add(X,Y)
np.subtract(X,Y)
np.multiply(X,Y)
np.divide(X,Y)

In [ ]:
# apply mathematical functions to all elements of an ndarray at once
np.exp(x)
np.sqrt(x)
np.power(x,2)