In [3]:
import numpy as np
print(np.__version__)

1.23.5


2. How to create a 1D array?

In [4]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. How to create a boolean array?

In [8]:
np.full((3,3), True, dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
# or
np.full((9),True, dtype = bool).reshape(3,3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
# or
np.ones((3,3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
# or
np.ones((9), dtype = bool).reshape(3,3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. How to extract items that satisfy a given condition from 1D array?

In [15]:
# Question : Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])
x = np.arange(10)
x[x%2 == 1]

array([1, 3, 5, 7, 9])

5. How to replace items that satisfy a condition with another value in numpy array?

In [17]:
# Question: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr = np.arange(10)
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

 6. How to replace items that satisfy a condition without affecting the original array?

In [18]:
# Question: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output:
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.arange(10)
out = arr.copy()
out[out%2 == 1] = -1
print('Modified array:',out)
print('Original array',arr)

Modified array: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
Original array [0 1 2 3 4 5 6 7 8 9]


7. How to reshape an array?

In [19]:
# Question: Convert a 1D array to a 2D array with 2 rows
# input: np.arange(10)
# output array([[0, 1, 2, 3, 4],
#               [5, 6, 7, 8, 9]])
arr = np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
# or
arr = np.arange(10)
arr.reshape(2,-1)   # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. How to stack two arrays vertically?

In [21]:
# Question: Stack arrays a and b vertically
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
# output: array([[0, 1, 2, 3, 4],
#                [5, 6, 7, 8, 9],
#                [1, 1, 1, 1, 1],
#                [1, 1, 1, 1, 1]])
a = np.arange(10).reshape(2,5)
b = np.repeat(1,10).reshape(2,5)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. How to stack two arrays horizontally?

In [22]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. How to generate custom sequences in numpy without hardcoding?



In [23]:
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1,2,3])
np.hstack((np.repeat(a, 3), np.tile(a, 3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

11. How to get the common items between two python numpy arrays?

In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

12. How to remove from one array those items that exist in another?

In [26]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

13. How to get the positions where elements of two arrays match?

In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

14. How to extract all numbers between a given range from a numpy array?

In [29]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

15. How to make a python function that handles scalars to work on numpy arrays?


In [31]:
def maxx(x, y):
  if x >= y:
    return x
  else:
    return y

def pair_max(x, y):
  maximum = [maxx(a,b) for a,b in map(lambda a,b:(a,b),x,y)]
  return np.array(maximum)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

16. How to swap two columns in a 2d numpy array?

In [33]:
arr = np.arange(9).reshape(3,3)

print('Original array',arr)

# Solution

print("\nModified array")
arr[:, [1,0,2]]

Original array [[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

17. How to swap two rows in a 2d numpy array?

In [34]:
arr = np.arange(9).reshape(3,3)
print('original:',arr)
arr[[1,0,2], :]

original: [[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])


18. How to reverse the rows of a 2D array?


In [36]:
arr = np.arange(9).reshape(3,3)

print('Original array',arr)

print("\nModified array")
arr[::-1, :]

Original array [[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

19. How to reverse the columns of a 2D array?

In [37]:
arr = np.arange(9).reshape(3,3)
print('Original array',arr)

print("\nModified array")
arr[:, ::-1]

Original array [[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

20. How to create a 2D array containing random floats between 5 and 10?

In [38]:
rand_arr = np.random.uniform(5,10, size = (5,3))
rand_arr

array([[8.36863262, 5.04355671, 8.77553617],
       [9.22643482, 7.80002845, 7.32491086],
       [8.49340661, 8.70538381, 8.84299449],
       [7.37438396, 8.97490728, 9.77663562],
       [9.38528795, 6.71935741, 8.62419308]])